"""
Agent code templates using Jinja2
"""

# Template for generated agent Python files
AGENT_TEMPLATE = '''"""
{{ agent_name }} - Generated by AI Agent Factory
{{ description }}
"""
import os
import sys
from typing import Any, Optional

# Add project root to path for imports (go up from agents/<agent_name>/ to project root)
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from agent_factory.base_agent import BaseAgent


class {{ class_name }}(BaseAgent):
    """
    {{ description }}
    
    Capabilities: {{ capabilities|join(', ') }}
    Model: {{ model }}
    """
    
    @property
    def name(self) -> str:
        return "{{ agent_name }}"
    
    @property
    def description(self) -> str:
        return """{{ description }}"""
    
    @property
    def system_prompt(self) -> str:
        return """{{ system_prompt }}"""
    
    def __init__(
        self,
        model: str = "{{ model }}",
        temperature: float = {{ temperature }},
        max_tokens: int = {{ max_tokens }},
        api_key: Optional[str] = None
    ):
        super().__init__(
            model=model,
            temperature=temperature,
            max_tokens=max_tokens,
            api_key=api_key
        )
        self._setup_tools()
    
    def _setup_tools(self) -> None:
        """Initialize the agent's tools"""
        {% for tool in tools %}
        self.add_tool({
            "type": "function",
            "function": {
                "name": "{{ tool }}",
                "description": "Tool: {{ tool }}",
                "parameters": {"type": "object", "properties": {}}
            }
        })
        {% endfor %}
        pass
    
    {% if 'reasoning' in capabilities %}
    def reason(self, problem: str) -> str:
        """
        Apply step-by-step reasoning to solve a problem.
        
        Args:
            problem: The problem to reason about
            
        Returns:
            The reasoning result
        """
        reasoning_prompt = f"""
        Please solve this problem step by step:
        
        {problem}
        
        Think through each step carefully and show your reasoning.
        """
        return self.chat(reasoning_prompt)
    {% endif %}
    
    {% if 'code_generation' in capabilities %}
    def generate_code(self, specification: str, language: str = "python") -> str:
        """
        Generate code based on a specification.
        
        Args:
            specification: What the code should do
            language: Programming language to use
            
        Returns:
            Generated code
        """
        code_prompt = f"""
        Generate {language} code for the following specification:
        
        {specification}
        
        Provide clean, well-documented code with proper error handling.
        """
        return self.chat(code_prompt)
    {% endif %}
    
    {% if 'task_planning' in capabilities %}
    def plan_task(self, task: str) -> str:
        """
        Create a detailed plan for completing a task.
        
        Args:
            task: The task to plan
            
        Returns:
            A structured task plan
        """
        planning_prompt = f"""
        Create a detailed, actionable plan for the following task:
        
        {task}
        
        Break it down into clear steps with estimated effort.
        """
        return self.chat(planning_prompt)
    {% endif %}
    
    {% if 'data_analysis' in capabilities %}
    def analyze_data(self, data_description: str) -> str:
        """
        Analyze data based on a description.
        
        Args:
            data_description: Description of the data to analyze
            
        Returns:
            Analysis results and insights
        """
        analysis_prompt = f"""
        Analyze the following data and provide insights:
        
        {data_description}
        
        Include key findings, patterns, and recommendations.
        """
        return self.chat(analysis_prompt)
    {% endif %}


def main():
    """Run the agent in interactive mode"""
    agent = {{ class_name }}()
    agent.run()


if __name__ == "__main__":
    main()
'''

# Template for agent __init__.py
AGENT_INIT_TEMPLATE = '''"""
{{ agent_name }} Agent Package
"""
from .{{ module_name }} import {{ class_name }}

__all__ = ["{{ class_name }}"]
'''

# Template for agent README
AGENT_README_TEMPLATE = '''# {{ agent_name }}

{{ description }}

## Capabilities

{% for cap in capabilities %}
- {{ cap }}
{% endfor %}

## Usage

```python
from agents.{{ module_name }}.{{ module_name }} import {{ class_name }}

# Create an instance
agent = {{ class_name }}()

# Chat with the agent
response = agent.chat("Hello!")
print(response)

# Run interactively
agent.run()
```

## Configuration

- **Model**: {{ model }}
- **Temperature**: {{ temperature }}
- **Max Tokens**: {{ max_tokens }}

## Generated By

This agent was generated by the AI Agent Factory.
'''
